workflows:
  android_build:
    name: "QuranGND"
    environment:
      android: "30"

    # Define the workflow stages
    scripts:
      - name: checkout_repository
        script: |
           git clone https://github.com/TechBeeps/GND-App.git

     - name: setup_dependencies
        script: |
          cd your_android_app
          ./gradlew dependencies

      - name: build_apk
        script: |
          ./gradlew assembleRelease

    # Define workflows' cache dependencies
    cache:
      directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
