workflows:
  android_build:
    name: "QuranGND"

    # Define the workflow stages
    stages:
      - name: Checkout repository
        script: git clone https://github.com/TechBeeps/GND-App.git

      - name: Setup dependencies
        script: |
          cd GND-App
          ./gradlew dependencies

      - name: Build APK
        script: ./gradlew assembleRelease

    # Define workflows' cache dependencies
    cache:
      directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
